### PR TITLE
just set up sha, will start work soon

### PR DESCRIPTION
**Pull request by Horlakz**

### CODE REVIEW

**Comment by Horlakz** [comment]
`yarn` to install packages
`yarn start` to run server
runs on port 5000 by default
so basically, `/` sends a string and posting to `/` also sends a string
to show the server is working
you can also use `npm install` to install packages

**Review by struckchure — APPROVED** [review]
check this out, to organize the routes

https://github.com/expressjs/express/tree/master/examples/route-map

**Comment by Horlakz** [comment]
> check this out, to organize the routes
> 
> https://github.com/expressjs/express/tree/master/examples/route-map

this one pass my power oo
but the routes are organized normally nau, why map again
@mjay0100 please check this out

**Comment by struckchure** [comment]
@Horlakz Maybe I'll just try to set it up myself, MJ should be able to do it if he's available today, it's not too complex, you don't have to follow their exact pattern, just find a way to organize it

**Comment by Horlakz** [comment]
alright no prob then

**Pull request merged**
